### PR TITLE
unswapped width and height in resize in history processor

### PR DESCRIPTION
**Pull request by howard-abrams**
unswapped width and height in resize and final reshape in history processor re:issue https://github.com/deeplearning4j/rl4j/issues/30

### CODE REVIEW

**Comment by saudet** [comment]
We only need to swap the ones in Size(), the other ones are correct.

**Comment by howard-abrams** [comment]
ok, later today I can output some transformed images to prove or disprove that.

**Comment by howard-abrams** [comment]
Ok, rebased with just the swap in resize.  But I'm a bit confused on why the mat is allocated with height x width when the previous mats are width x height.

**Comment by saudet** [comment]
Great, thanks!

Which "previous mats" are you talking about? All the ones allocated in the same file are given the "height" and "width" in that order.

**Comment by howard-abrams** [comment]
Never mind on the mat swap, I must have been looking at the wrong variable when I wrote that comment. All seems good.

**Comment by howard-abrams** [comment]
Forgive me for dragging this on, but if the output of transform is
`out = out.reshape(1, conf.getCroppingHeight(), conf.getCroppingWidth());`

why is the shape from IHistoryProcessor the reverse?
`return new int[] {getHistoryLength(), getCroppingWidth(), getCroppingHeight()};`

**Comment by rubenfiszel** [comment]
Yes, this seems wrong. shape from IHistoryProcessor and reshape should be coherent.

It shouldn't be too hard to test to make sure of the right order (get the shape of the matrix out after: 
`out = new NativeImageLoader(conf.getCroppingHeight(), conf.getCroppingWidth()).asMatrix(cropped);`
this should be the true order.

**Comment by howard-abrams** [comment]
For my input that has a cropping width of 160 and a height of 80, the shape of 
`out = new NativeImageLoader(conf.getCroppingHeight(), conf.getCroppingWidth()).asMatrix(cropped);`
is
`[1,1,80,160]`

The current shape in IHistoryProcessor is:
`[1, 160, 80]`

am I correct in thinking that the shape from IHistoryProcessor should be:
`[1, 80, 160]`
?

**Comment by rubenfiszel** [comment]
Yes, you're correct.

**Comment by howard-abrams** [comment]
are you able to checkin that fix or do you need me to create another PR?

**Comment by rubenfiszel** [comment]
I committed directly 4e2b52e
Thanks.

**Comment by howard-abrams** [comment]
Thanks!

**Pull request merged**
