### PR TITLE
Stop type leakage in EpsGreedy

### PR DESCRIPTION
**Pull request by pokowaka**
- Previously this class exposed the generic AS, which is unused and not
  externally visible. We now make this type internal, simplifying the
  code.

- Risk of breaking change is minimal as this is a protected getter.

Test: mvn install succeeds.

## What changes were proposed in this pull request?

The training policy is leaking types.

## How was this patch tested?

mvn install succeeds.

### CODE REVIEW

**Comment by saudet** [comment]
Thanks, but you're adding other stuff like HasActionSpace and StepCounter. Could you explain a bit more what this is all about?

Also, your IDE seems to be undoing a lot of the formatting done by "mvn formatter:format". Could you maybe run that? Thanks!

**Comment by pokowaka** [comment]
Oh yes, the second commit should not be part of this. I will update the  change list and fix the editing issues.

**Comment by huitseeker** [comment]
@pokowaka Any news on rebasing and cleaning up this PR?

**Comment by AlexDBlack** [comment]
Closing this as outdated, in preparation for archiving this repo after migrating RL4J to mono repository here: https://github.com/deeplearning4j/deeplearning4j

**Pull request closed without merging**
