### PR TITLE
Migrate core classes to rl4j-api, anticipate gym deprecation

### PR DESCRIPTION
**Pull request by crockpotveggies**
## What changes were proposed in this pull request?

rl4j-api MDP interface depends on core classes from the java gym client. This is awkward since the MDP model is expansive beyond the gym and can be used in a variety of cases. This PR migrates these classes to the rl4j-api in anticipation of gym deprecation.

## How was this patch tested?

Manual tests and local integration.

### CODE REVIEW

**Comment by saudet** [comment]
Like I explained before, because rl4j depends on gym-java-client, gym-java-client cannot depend on rl4j!

**Comment by crockpotveggies** [comment]
Hmm I thought you were saying that the `gym-java-client` was being deprecated?

**Comment by saudet** [comment]
If we can get something working better with Jython 2.7.1 or what not, you bet it will get deprecated! Actually, I don't really see the point of having gym-java-client as a separate project. gym-http-api is such a poor hack, we should just have all this hidden under rl4j-gym and forget anything else ever existed :) What do you think @rubenfiszel? @agibsonccc?

**Comment by rubenfiszel** [comment]
The point of using gym-java-client as a separate project is that it is (or
was) the only way to interface with gym from Java, using rl4j or not. I do
not know if other projects are using it but it would be good practice to
not remove self-contained project that others might rely on.

If you do use Jython for interfacing, then I agree it would be much nicer
to not rely on http anymore and hide the interfacing under rl4j-gym but
that should only result in no dependency anymore on gym-java-client.

For coherence purposes, I would advice to copy rl4j-api classes to
gym-java-client and to rl4j-core so that there is no more
inter-dependencies. Moving classes that are not interfaces to rl4j-api
seems a bad idea to me.

**Comment by huitseeker** [comment]
@crockpotveggies I think we should close this given the comments by @rubenfiszel here, what's your take on it?

**Comment by crockpotveggies** [comment]
Agreed that this needs to be closed. However, I do think we need a plan for RL4J moving forward. I'd advocate merging this with the main DL4J repository, and fixing any(?) design issues if needed.

**Pull request closed without merging**
